// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/liatrio/rode-api/protodeps/grafeas/proto/v1beta1/grafeas_go_proto (interfaces: GrafeasV1Beta1Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	grafeas_go_proto "github.com/liatrio/rode-api/protodeps/grafeas/proto/v1beta1/grafeas_go_proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
)

// MockGrafeasV1Beta1Client is a mock of GrafeasV1Beta1Client interface
type MockGrafeasV1Beta1Client struct {
	ctrl     *gomock.Controller
	recorder *MockGrafeasV1Beta1ClientMockRecorder
}

// MockGrafeasV1Beta1ClientMockRecorder is the mock recorder for MockGrafeasV1Beta1Client
type MockGrafeasV1Beta1ClientMockRecorder struct {
	mock *MockGrafeasV1Beta1Client
}

// NewMockGrafeasV1Beta1Client creates a new mock instance
func NewMockGrafeasV1Beta1Client(ctrl *gomock.Controller) *MockGrafeasV1Beta1Client {
	mock := &MockGrafeasV1Beta1Client{ctrl: ctrl}
	mock.recorder = &MockGrafeasV1Beta1ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGrafeasV1Beta1Client) EXPECT() *MockGrafeasV1Beta1ClientMockRecorder {
	return m.recorder
}

// BatchCreateNotes mocks base method
func (m *MockGrafeasV1Beta1Client) BatchCreateNotes(arg0 context.Context, arg1 *grafeas_go_proto.BatchCreateNotesRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.BatchCreateNotesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchCreateNotes", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.BatchCreateNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateNotes indicates an expected call of BatchCreateNotes
func (mr *MockGrafeasV1Beta1ClientMockRecorder) BatchCreateNotes(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateNotes", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).BatchCreateNotes), varargs...)
}

// BatchCreateOccurrences mocks base method
func (m *MockGrafeasV1Beta1Client) BatchCreateOccurrences(arg0 context.Context, arg1 *grafeas_go_proto.BatchCreateOccurrencesRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.BatchCreateOccurrencesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchCreateOccurrences", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.BatchCreateOccurrencesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateOccurrences indicates an expected call of BatchCreateOccurrences
func (mr *MockGrafeasV1Beta1ClientMockRecorder) BatchCreateOccurrences(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateOccurrences", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).BatchCreateOccurrences), varargs...)
}

// CreateNote mocks base method
func (m *MockGrafeasV1Beta1Client) CreateNote(arg0 context.Context, arg1 *grafeas_go_proto.CreateNoteRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateNote", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote
func (mr *MockGrafeasV1Beta1ClientMockRecorder) CreateNote(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).CreateNote), varargs...)
}

// CreateOccurrence mocks base method
func (m *MockGrafeasV1Beta1Client) CreateOccurrence(arg0 context.Context, arg1 *grafeas_go_proto.CreateOccurrenceRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Occurrence, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOccurrence", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Occurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOccurrence indicates an expected call of CreateOccurrence
func (mr *MockGrafeasV1Beta1ClientMockRecorder) CreateOccurrence(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOccurrence", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).CreateOccurrence), varargs...)
}

// DeleteNote mocks base method
func (m *MockGrafeasV1Beta1Client) DeleteNote(arg0 context.Context, arg1 *grafeas_go_proto.DeleteNoteRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteNote", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNote indicates an expected call of DeleteNote
func (mr *MockGrafeasV1Beta1ClientMockRecorder) DeleteNote(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).DeleteNote), varargs...)
}

// DeleteOccurrence mocks base method
func (m *MockGrafeasV1Beta1Client) DeleteOccurrence(arg0 context.Context, arg1 *grafeas_go_proto.DeleteOccurrenceRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOccurrence", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOccurrence indicates an expected call of DeleteOccurrence
func (mr *MockGrafeasV1Beta1ClientMockRecorder) DeleteOccurrence(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOccurrence", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).DeleteOccurrence), varargs...)
}

// GetNote mocks base method
func (m *MockGrafeasV1Beta1Client) GetNote(arg0 context.Context, arg1 *grafeas_go_proto.GetNoteRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNote", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote
func (mr *MockGrafeasV1Beta1ClientMockRecorder) GetNote(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).GetNote), varargs...)
}

// GetOccurrence mocks base method
func (m *MockGrafeasV1Beta1Client) GetOccurrence(arg0 context.Context, arg1 *grafeas_go_proto.GetOccurrenceRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Occurrence, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOccurrence", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Occurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOccurrence indicates an expected call of GetOccurrence
func (mr *MockGrafeasV1Beta1ClientMockRecorder) GetOccurrence(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOccurrence", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).GetOccurrence), varargs...)
}

// GetOccurrenceNote mocks base method
func (m *MockGrafeasV1Beta1Client) GetOccurrenceNote(arg0 context.Context, arg1 *grafeas_go_proto.GetOccurrenceNoteRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOccurrenceNote", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOccurrenceNote indicates an expected call of GetOccurrenceNote
func (mr *MockGrafeasV1Beta1ClientMockRecorder) GetOccurrenceNote(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOccurrenceNote", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).GetOccurrenceNote), varargs...)
}

// GetVulnerabilityOccurrencesSummary mocks base method
func (m *MockGrafeasV1Beta1Client) GetVulnerabilityOccurrencesSummary(arg0 context.Context, arg1 *grafeas_go_proto.GetVulnerabilityOccurrencesSummaryRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.VulnerabilityOccurrencesSummary, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVulnerabilityOccurrencesSummary", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.VulnerabilityOccurrencesSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVulnerabilityOccurrencesSummary indicates an expected call of GetVulnerabilityOccurrencesSummary
func (mr *MockGrafeasV1Beta1ClientMockRecorder) GetVulnerabilityOccurrencesSummary(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVulnerabilityOccurrencesSummary", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).GetVulnerabilityOccurrencesSummary), varargs...)
}

// ListNoteOccurrences mocks base method
func (m *MockGrafeasV1Beta1Client) ListNoteOccurrences(arg0 context.Context, arg1 *grafeas_go_proto.ListNoteOccurrencesRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.ListNoteOccurrencesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListNoteOccurrences", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.ListNoteOccurrencesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNoteOccurrences indicates an expected call of ListNoteOccurrences
func (mr *MockGrafeasV1Beta1ClientMockRecorder) ListNoteOccurrences(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNoteOccurrences", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).ListNoteOccurrences), varargs...)
}

// ListNotes mocks base method
func (m *MockGrafeasV1Beta1Client) ListNotes(arg0 context.Context, arg1 *grafeas_go_proto.ListNotesRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.ListNotesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListNotes", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.ListNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes
func (mr *MockGrafeasV1Beta1ClientMockRecorder) ListNotes(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).ListNotes), varargs...)
}

// ListOccurrences mocks base method
func (m *MockGrafeasV1Beta1Client) ListOccurrences(arg0 context.Context, arg1 *grafeas_go_proto.ListOccurrencesRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.ListOccurrencesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOccurrences", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.ListOccurrencesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOccurrences indicates an expected call of ListOccurrences
func (mr *MockGrafeasV1Beta1ClientMockRecorder) ListOccurrences(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOccurrences", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).ListOccurrences), varargs...)
}

// UpdateNote mocks base method
func (m *MockGrafeasV1Beta1Client) UpdateNote(arg0 context.Context, arg1 *grafeas_go_proto.UpdateNoteRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateNote", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote
func (mr *MockGrafeasV1Beta1ClientMockRecorder) UpdateNote(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).UpdateNote), varargs...)
}

// UpdateOccurrence mocks base method
func (m *MockGrafeasV1Beta1Client) UpdateOccurrence(arg0 context.Context, arg1 *grafeas_go_proto.UpdateOccurrenceRequest, arg2 ...grpc.CallOption) (*grafeas_go_proto.Occurrence, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOccurrence", varargs...)
	ret0, _ := ret[0].(*grafeas_go_proto.Occurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOccurrence indicates an expected call of UpdateOccurrence
func (mr *MockGrafeasV1Beta1ClientMockRecorder) UpdateOccurrence(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOccurrence", reflect.TypeOf((*MockGrafeasV1Beta1Client)(nil).UpdateOccurrence), varargs...)
}
