// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	grafeas_go_proto "github.com/grafeas/grafeas/proto/v1beta1/grafeas_go_proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RodeCollectorServiceClient is the client API for RodeCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RodeCollectorServiceClient interface {
	BatchCreateOccurrences(ctx context.Context, in *grafeas_go_proto.BatchCreateOccurrencesRequest, opts ...grpc.CallOption) (*grafeas_go_proto.BatchCreateOccurrencesResponse, error)
}

type rodeCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRodeCollectorServiceClient(cc grpc.ClientConnInterface) RodeCollectorServiceClient {
	return &rodeCollectorServiceClient{cc}
}

func (c *rodeCollectorServiceClient) BatchCreateOccurrences(ctx context.Context, in *grafeas_go_proto.BatchCreateOccurrencesRequest, opts ...grpc.CallOption) (*grafeas_go_proto.BatchCreateOccurrencesResponse, error) {
	out := new(grafeas_go_proto.BatchCreateOccurrencesResponse)
	err := c.cc.Invoke(ctx, "/rode.v1alpha1.RodeCollectorService/BatchCreateOccurrences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RodeCollectorServiceServer is the server API for RodeCollectorService service.
// All implementations must embed UnimplementedRodeCollectorServiceServer
// for forward compatibility
type RodeCollectorServiceServer interface {
	BatchCreateOccurrences(context.Context, *grafeas_go_proto.BatchCreateOccurrencesRequest) (*grafeas_go_proto.BatchCreateOccurrencesResponse, error)
	mustEmbedUnimplementedRodeCollectorServiceServer()
}

// UnimplementedRodeCollectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRodeCollectorServiceServer struct {
}

func (UnimplementedRodeCollectorServiceServer) BatchCreateOccurrences(context.Context, *grafeas_go_proto.BatchCreateOccurrencesRequest) (*grafeas_go_proto.BatchCreateOccurrencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateOccurrences not implemented")
}
func (UnimplementedRodeCollectorServiceServer) mustEmbedUnimplementedRodeCollectorServiceServer() {}

// UnsafeRodeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RodeCollectorServiceServer will
// result in compilation errors.
type UnsafeRodeCollectorServiceServer interface {
	mustEmbedUnimplementedRodeCollectorServiceServer()
}

func RegisterRodeCollectorServiceServer(s grpc.ServiceRegistrar, srv RodeCollectorServiceServer) {
	s.RegisterService(&_RodeCollectorService_serviceDesc, srv)
}

func _RodeCollectorService_BatchCreateOccurrences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(grafeas_go_proto.BatchCreateOccurrencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RodeCollectorServiceServer).BatchCreateOccurrences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rode.v1alpha1.RodeCollectorService/BatchCreateOccurrences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RodeCollectorServiceServer).BatchCreateOccurrences(ctx, req.(*grafeas_go_proto.BatchCreateOccurrencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RodeCollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rode.v1alpha1.RodeCollectorService",
	HandlerType: (*RodeCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchCreateOccurrences",
			Handler:    _RodeCollectorService_BatchCreateOccurrences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1alpha1/rode.proto",
}
